# Generated by Django 5.2.8 on 2026-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_remove_reaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], null=True, verbose_name='reaction'),
        ),
    ]
