# Generated by Django 5.2.8 on 2026-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_alter_reaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], null=True, verbose_name='reaction'),
        ),
    ]
